const resList = [
    {
      id: 1,
      name: "Udupi",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 4.2,
      deliveryTime: 30,
    },
    {
      id: 2,
      name: "Res B",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 4.3,
      deliveryTime: 30,
    },
    {
      id: 3,
      name: "Res C",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 4,
      name: "Res D",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 5,
      name: "Res E",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 6,
      name: "Udupi",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 7,
      name: "Res B",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 8,
      name: "Res C",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 9,
      name: "Res D",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 10,
      name: "Res E",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 11,
      name: "Udupi",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 12,
      name: "Res B",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 13,
      name: "Res C",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 14,
      name: "Res D",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
    {
      id: 15,
      name: "Res E",
      cusine: ["Dosa", "Vada", "Idli"],
      rating: 3.8,
      deliveryTime: 30,
    },
  ];

  export default resList